"""
Pydantic models and sample data for the Job Finder assistant.
Phase 3: AI Logic scaffolding
"""

from __future__ import annotations

from typing import List, Optional
from datetime import datetime
from pydantic import BaseModel, Field


class JobSeekerProfile(BaseModel):
    """Structured representation of a job seeker's preferences."""

    id: Optional[str] = None
    current_role: Optional[str] = None
    skills: List[str] = Field(default_factory=list)
    years_experience: Optional[int] = None
    preferred_titles: List[str] = Field(default_factory=list)
    preferred_locations: List[str] = Field(default_factory=list)
    salary_expectation: Optional[str] = None
    work_type: Optional[str] = None  # remote / onsite / hybrid
    industries: List[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    user_id: Optional[str] = None


class JobListing(BaseModel):
    """Structured job listing pulled from internal database."""

    id: str
    title: str
    company: str
    location: str
    required_skills: List[str]
    optional_skills: List[str] = Field(default_factory=list)
    experience_level: Optional[str] = None
    salary_range: Optional[str] = None
    work_type: Optional[str] = None
    industries: List[str] = Field(default_factory=list)
    description: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)


class JobRecommendation(BaseModel):
    """Job recommendation generated by the matching agent."""

    id: str
    job_id: str
    seeker_id: str
    match_score: int
    explanation: str
    created_at: datetime = Field(default_factory=datetime.utcnow)


class JobFinderSession(BaseModel):
    """State container for an in-progress job finder session."""

    session_id: str
    seeker_profile: JobSeekerProfile
    messages: List[dict] = Field(default_factory=list)
    recommendations: List[JobRecommendation] = Field(default_factory=list)
    is_profile_complete: bool = False


SAMPLE_JOB_LISTINGS: List[JobListing] = [
    JobListing(
        id="job-001",
        title="Senior Frontend Engineer",
        company="Nova Labs",
        location="Remote (US)",
        required_skills=["react", "typescript", "design systems"],
        optional_skills=["storybook", "tailwind"],
        experience_level="senior",
        salary_range="$150k - $170k",
        work_type="remote",
        industries=["software", "developer tools"],
        description="Own the design system for a multimillion-user product.",
    ),
    JobListing(
        id="job-002",
        title="Product Designer (Growth)",
        company="Atlas AI",
        location="Austin, TX (Hybrid)",
        required_skills=["figma", "user research", "prototyping"],
        optional_skills=["motion design"],
        experience_level="mid",
        salary_range="$120k - $140k",
        work_type="hybrid",
        industries=["ai", "saas"],
        description="Design experiments for AI onboarding funnels.",
    ),
    JobListing(
        id="job-003",
        title="Data Analyst",
        company="BluePeak Consulting",
        location="New York, NY (On-site)",
        required_skills=["sql", "looker", "storytelling"],
        optional_skills=["python", "dbt"],
        experience_level="mid",
        salary_range="$100k - $120k",
        work_type="onsite",
        industries=["consulting"],
        description="Help Fortune 500 clients derive insights from BI dashboards.",
    ),
    # Full Stack Developer positions (matching user profile)
    JobListing(
        id="job-004",
        title="Full Stack Developer",
        company="TechHub Jordan",
        location="Amman, Jordan (On-site)",
        required_skills=["react", "nodejs", "typescript", "mongodb"],
        optional_skills=["next.js", "tailwind", "docker"],
        experience_level="mid",
        salary_range="JOD 1000-1500/month",
        work_type="onsite",
        industries=["software", "fintech"],
        description="Build full-stack web applications using React and Node.js. Work with modern tech stack.",
    ),
    JobListing(
        id="job-005",
        title="Full Stack Engineer (React & Node.js)",
        company="DigitalWave",
        location="Amman, Jordan (On-site)",
        required_skills=["react", "javascript", "node.js", "sql"],
        optional_skills=["typescript", "nextjs", "aws"],
        experience_level="mid",
        salary_range="JOD 900-1300/month",
        work_type="onsite",
        industries=["e-commerce", "software"],
        description="Develop full-stack applications with React frontend and Node.js backend. Join our growing team.",
    ),
    JobListing(
        id="job-006",
        title="Senior Full Stack Developer",
        company="InnovateTech MENA",
        location="Amman, Jordan (On-site)",
        required_skills=["react", "typescript", "nodejs", "postgresql"],
        optional_skills=["nextjs", "graphql", "kubernetes"],
        experience_level="senior",
        salary_range="JOD 1500-2000/month",
        work_type="onsite",
        industries=["software", "saas"],
        description="Lead development of enterprise full-stack applications. Mentor junior developers.",
    ),
    JobListing(
        id="job-007",
        title="Full Stack Developer (Hybrid)",
        company="CloudNine Solutions",
        location="Beirut, Lebanon (Hybrid)",
        required_skills=["react", "node.js", "javascript", "mongodb"],
        optional_skills=["vue", "express", "docker"],
        experience_level="mid",
        salary_range="$2000-3000/month",
        work_type="hybrid",
        industries=["software", "fintech"],
        description="Build scalable full-stack web applications. Work 2 days office, 3 days remote.",
    ),
    JobListing(
        id="job-008",
        title="Frontend Developer (React)",
        company="Pixel Perfect Studio",
        location="Amman, Jordan (On-site)",
        required_skills=["react", "javascript", "css"],
        optional_skills=["typescript", "next.js", "tailwind"],
        experience_level="junior",
        salary_range="JOD 400-600/month",
        work_type="onsite",
        industries=["design", "software"],
        description="Create beautiful and responsive UIs with React. Great for learning and growth.",
    ),
    JobListing(
        id="job-009",
        title="Full Stack Developer (MERN Stack)",
        company="StartupHub Arabia",
        location="Dubai, UAE (On-site)",
        required_skills=["react", "nodejs", "express", "mongodb"],
        optional_skills=["typescript", "redis", "aws"],
        experience_level="mid",
        salary_range="AED 5000-7000/month",
        work_type="onsite",
        industries=["fintech", "e-commerce"],
        description="Work on MERN stack applications. Fast-growing startup with great learning opportunities.",
    ),
    JobListing(
        id="job-010",
        title="Backend Developer (Node.js)",
        company="CodeForce",
        location="Amman, Jordan (On-site)",
        required_skills=["nodejs", "javascript", "postgresql"],
        optional_skills=["typescript", "graphql", "docker"],
        experience_level="mid",
        salary_range="JOD 900-1200/month",
        work_type="onsite",
        industries=["software"],
        description="Build scalable APIs and microservices with Node.js. Remote work available after probation.",
    ),
]


